# Generated by Django 4.1.5 on 2023-01-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('age', models.CharField(max_length=3)),
                ('gender', models.CharField(max_length=6)),
                ('symptoms', models.TextField(max_length=122)),
            ],
        ),
    ]
